{% set version = "3.7.0" %}

package:
  name: anyio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/a/anyio/anyio-{{ version }}.tar.gz
    sha256: 275d9973793619a5374e1c89a4f4ad3f4b0a5510a2b5b939444bee8f4c4d37ce
  - folder: src
    url: https://github.com/agronholm/anyio/archive/{{ version }}.tar.gz
    sha256: 2f8c7bede49fa8344a96feee63de52fb9b02881dc3137cd4b5cc770d5cc4b436

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm >=3.4
  run:
    # - exceptiongroup  # >=3.6.2
    - idna >=2.8
    - python >=3.7
    - sniffio >=1.1
    - typing_extensions
  run_constrained:
    # - trio >=0.22  # >=3.6.2
    - trio >=0.16,<0.22

test:
  source_files:
    - src/tests
    - src/pyproject.toml
  requires:
    - coverage >=4.5
    - trio
    - hypothesis >=4.0
    - mock >=4
    - pip
    - pytest >=6.0
    - pytest-cov
    - pytest-mock >=3.6.1
    - toml
    - trustme
    # won't be available on pypy, or windows, any time soon
    - uvloop >=0.17  # [unix and python_impl == 'cpython']
  imports:
    - anyio
  commands:
    - pip check

about:
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  doc_url: https://anyio.readthedocs.io
  doc_source_url: https://github.com/agronholm/anyio/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
